# Generated by Django 6.0.6 on 2026-06-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_ingredients_choices_to_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='choices',
        ),
    ]
