from django.core.management.base import BaseCommand
from apps.products.models import Product


PRODUCTS = [
    # ── POKE ──────────────────────────────────────────────────────────────────
    {
        'name': 'Poke Atún Fresco',
        'description': 'Poke bowl con base de arroz sushi, deliciosa salsa de ostión especial, col morada, zanahoria, pepino y dados de atún fresco.',
        'sku': 'POKE-ATU-01',
        'unit_price': '29.90',
        'stock': 40,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'atún fresco', 'salsa ostión', 'col morada', 'zanahoria', 'pepino'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/u6zbbYZ4AQ6Qo5cSR-300-x.webp',
    },
    {
        'name': 'Poke Ebi Furai',
        'description': 'Poke bowl con base de arroz sushi, deliciosa salsa de ostión especial, col morada, zanahoria, pepino y langostinos empanizados.',
        'sku': 'POKE-EBI-02',
        'unit_price': '29.90',
        'stock': 40,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'ebi furai', 'salsa ostión', 'col morada', 'zanahoria', 'pepino'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/XMHRtBkDsPAPDBoRb-300-x.webp',
    },
    {
        'name': 'Poke Langostino Cocido',
        'description': 'Poke bowl con base de arroz sushi, deliciosa salsa de ostión especial, col morada, zanahoria, pepino y langostinos blanqueados.',
        'sku': 'POKE-LAN-03',
        'unit_price': '29.90',
        'stock': 40,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'langostino cocido', 'salsa ostión', 'col morada', 'zanahoria', 'pepino'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/KZKDGWGfzm4StG7vg-300-x.webp',
    },
    {
        'name': 'Poke Pulpa Mix',
        'description': 'Poke bowl con base de arroz sushi, deliciosa salsa de ostión especial, col morada, zanahoria, pepino y crema de cangrejo.',
        'sku': 'POKE-PUL-04',
        'unit_price': '29.90',
        'stock': 40,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'pulpa mix', 'salsa ostión', 'col morada', 'zanahoria', 'pepino'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/8snqM7gFf8jLz3x7s-300-x.webp',
    },
    {
        'name': 'Poke Sakana Furai',
        'description': 'Poke bowl con base de arroz sushi, deliciosa salsa de ostión especial, col morada, zanahoria, pepino y bastones de pescado frito.',
        'sku': 'POKE-SAK-05',
        'unit_price': '29.90',
        'stock': 40,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'sakana furai', 'salsa ostión', 'col morada', 'zanahoria', 'pepino'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/v8dmAaWEzLeNjm3Mp-300-x.webp',
    },
    {
        'name': 'Poke Salmón Fresco',
        'description': 'Poke bowl con base de arroz sushi, deliciosa salsa de ostión especial, col morada, zanahoria, pepino y dados de salmón fresco.',
        'sku': 'POKE-SAL-06',
        'unit_price': '29.90',
        'stock': 40,
        'is_featured': True,
        'ingredients': ['arroz sushi', 'salmón fresco', 'salsa ostión', 'col morada', 'zanahoria', 'pepino'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/Z7NvgrHgp7gJNr9Gv-300-x.webp',
    },
    {
        'name': 'Poke Tartar de Trucha',
        'description': 'Poke bowl con base de arroz sushi, deliciosa salsa de ostión especial, col morada, zanahoria, pepino y tartar de trucha con ajonjolí.',
        'sku': 'POKE-TAR-07',
        'unit_price': '29.90',
        'stock': 40,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'tartar de trucha', 'ajonjolí', 'salsa ostión', 'col morada', 'zanahoria'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/rdAaDdXgZ5guJXpWY-300-x.webp',
    },
    {
        'name': 'Poke de Trucha',
        'description': 'Poke bowl con base de arroz sushi, deliciosa salsa de ostión especial, col morada, zanahoria, pepino y dados de trucha asalmonada.',
        'sku': 'POKE-TRU-08',
        'unit_price': '27.90',
        'stock': 40,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'trucha', 'salsa ostión', 'col morada', 'zanahoria', 'pepino'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/Ydrv4AgzHxpmJkJ4n-300-x.webp',
    },
    # ── MAKIS ─────────────────────────────────────────────────────────────────
    {
        'name': 'Acevichado Maki',
        'description': 'Roll de langostino empanizado y palta, cubierto con láminas frescas de pescado blanco. Con toques de salsa acevichada.',
        'sku': 'MAKI-ACE-09',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': True,
        'ingredients': ['langostino empanizado', 'palta', 'pescado blanco', 'salsa acevichada'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/xL89gzB5ez2PA2MAz-300-x.webp',
    },
    {
        'name': 'Baby Maki',
        'description': 'Relleno de ebi furai y palta, cubierto con trucha y nuestra salsa baby ligeramente picante.',
        'sku': 'MAKI-BAB-10',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': True,
        'ingredients': ['ebi furai', 'palta', 'trucha', 'salsa baby'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/GbnXH8GvxWuF9u65Z-300-x.webp',
    },
    {
        'name': 'California Maki',
        'description': 'Roll de langostino blanqueado, queso crema y frescos bastones de palta, envuelto en ajonjolí.',
        'sku': 'MAKI-CAL-11',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': True,
        'ingredients': ['langostino blanqueado', 'queso crema', 'palta', 'ajonjolí'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/uzTynC2gG7dY3GfGm-300-x.webp',
    },
    {
        'name': 'Ceviche Maki',
        'description': 'Relleno de pescado marinado en jugo de ceviche y langostino empanizado, cubierto con zanahoria.',
        'sku': 'MAKI-CEV-12',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['pescado marinado', 'langostino empanizado', 'jugo de ceviche', 'zanahoria'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/kbtnawrmFMJEHLdM2-300-x.webp',
    },
    {
        'name': 'Furai Maki',
        'description': 'Roll empanizado al panko y frito, con queso crema, palta cremosa y jugosa trucha.',
        'sku': 'MAKI-FUR-13',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['panko', 'queso crema', 'palta', 'trucha'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/bNcuKaRawnENBGCYm-300-x.webp',
    },
    {
        'name': 'Hiroshima Maki',
        'description': 'Langostino empanizado y palta, cubierto con pescado blanco y gratinado con crema de parmesano.',
        'sku': 'MAKI-HIR-14',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['langostino empanizado', 'palta', 'pescado blanco', 'crema parmesano'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/82PzaXeXqwdxz2SP7-300-x.webp',
    },
    {
        'name': 'Huancaína Maki',
        'description': 'Roll relleno de langostino empanizado y palta, cubierto con láminas de pescado blanco y salsa huancaína.',
        'sku': 'MAKI-HUA-15',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['langostino empanizado', 'palta', 'pescado blanco', 'salsa huancaína'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/FyyAR4vsDBaqHw3m4-300-x.webp',
    },
    {
        'name': 'Inka Maki',
        'description': 'Roll relleno de trucha salmonada y palta, cubierto con ajonjolí mixto tostado.',
        'sku': 'MAKI-INK-16',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['trucha salmonada', 'palta', 'ajonjolí mixto'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/CgmqfE9HZdSHcHbzx-300-x.webp',
    },
    {
        'name': 'Kani Maki',
        'description': 'Roll relleno de langostino empanizado y palta, cubierto con una suave pasta de cangrejo.',
        'sku': 'MAKI-KAN-17',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['langostino empanizado', 'palta', 'pasta de cangrejo'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/zYtFCqmGhMDgXQtCD-300-x.webp',
    },
    {
        'name': 'Kudamono Maki',
        'description': 'Roll sin nori, relleno con queso crema y tuna crispy, cubierto con plátano frito y caramelo.',
        'sku': 'MAKI-KUD-18',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['queso crema', 'tuna crispy', 'plátano frito', 'caramelo'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/6NS4XT6RKCjJJ6YvQ-300-x.webp',
    },
    {
        'name': 'Lomo Saltado Maki',
        'description': 'Roll relleno de bastones de carne en tempura y papas al hilo, cubierto de láminas de lomo salteado.',
        'sku': 'MAKI-LOM-19',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['carne en tempura', 'papas al hilo', 'lomo saltado'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/Y8qrC3SWdfGK3WBhj-300-x.webp',
    },
    {
        'name': 'Monky Maki',
        'description': 'Roll sin nori, relleno de cremoso queso, palta y tuna crispy, envuelto en finas láminas de plátano dulce.',
        'sku': 'MAKI-MON-20',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['queso crema', 'palta', 'tuna crispy', 'plátano dulce'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/nas2cN5MC47hZWP2F-300-x.webp',
    },
    {
        'name': 'Mr. Sushi Maki',
        'description': 'Relleno de ebi furai y queso crema, cubierto de trucha y salsa ostión flameada.',
        'sku': 'MAKI-MRS-21',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': True,
        'ingredients': ['ebi furai', 'queso crema', 'trucha', 'salsa ostión'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/Ng4SGEeuMxCn7NDQa-300-x.webp',
    },
    {
        'name': 'Passion Maki',
        'description': 'Relleno de ebi furai y palta, cubierto con trucha flameada, salsa passion y cubierto de ajonjolí.',
        'sku': 'MAKI-PAS-22',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': True,
        'ingredients': ['ebi furai', 'palta', 'trucha flameada', 'salsa passion', 'ajonjolí'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/7gSnbZrqtdSwAu2vw-300-x.webp',
    },
    {
        'name': 'Philadelphia Maki',
        'description': 'Roll relleno de trucha y queso crema, cubierto de ajonjolí blanco. Acompañado de nuestra salsa especial.',
        'sku': 'MAKI-PHI-23',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['trucha', 'queso crema', 'ajonjolí blanco'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/s8YGoc2ehe2Yuupak-300-x.webp',
    },
    {
        'name': 'Quinua Maki',
        'description': 'Roll relleno de trucha asalmonada fresca, queso crema y crujientes bastones de palta, cubierto con quinua.',
        'sku': 'MAKI-QUI-24',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['trucha', 'queso crema', 'palta', 'quinua'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/zmYjoeTh8kqh98SBT-300-x.webp',
    },
    {
        'name': 'Tokio Maki',
        'description': 'Roll relleno de langostino empanizado y bastones de palta, cubierto de pulpa mix con crema picante.',
        'sku': 'MAKI-TOK-25',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['langostino empanizado', 'palta', 'pulpa mix', 'crema picante'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/w3bDDATjjyJuagqA7-300-x.webp',
    },
    {
        'name': 'Tuna Crispy',
        'description': 'Roll relleno de queso crema con pescado deshidratado y palta, cubierto con ajonjolí blanco.',
        'sku': 'MAKI-TUN-26',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['queso crema', 'pescado deshidratado', 'palta', 'ajonjolí blanco'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/dQWv63MGBGJLvPjHu-300-x.webp',
    },
    {
        'name': 'Yakuza Maki',
        'description': 'Roll relleno de langostino empanizado y queso crema, cubierto de palta y ajonjolí negro.',
        'sku': 'MAKI-YAK-27',
        'unit_price': '25.90',
        'stock': 60,
        'is_featured': False,
        'ingredients': ['langostino empanizado', 'queso crema', 'palta', 'ajonjolí negro'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/Bum5uJHb7usPFYCoz-300-x.webp',
    },
    # ── ENTRADAS FRÍAS ────────────────────────────────────────────────────────
    {
        'name': 'Gunkan Sushi de Kani',
        'description': 'Arroz envuelto en nori, relleno de pulpa de cangrejo y nuestra salsa especial.',
        'sku': 'ENTR-GKK-28',
        'unit_price': '15.90',
        'stock': 30,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'nori', 'pulpa de cangrejo'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/FDeXRyReZnXLf4GDE-300-x.webp',
    },
    {
        'name': 'Gunkan Sushi de Langostinos',
        'description': 'Arroz envuelto en nori, relleno de tartar de langostinos, cubitos de palta y nuestra salsa especial.',
        'sku': 'ENTR-GKL-29',
        'unit_price': '14.90',
        'stock': 30,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'nori', 'tartar de langostinos', 'palta'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/eEekaqAyZJuf2WnED-300-x.webp',
    },
    {
        'name': 'Gunkan Sushi de Trucha',
        'description': 'Arroz envuelto en nori, relleno de trucha y palta con nuestra salsa especial.',
        'sku': 'ENTR-GKT-30',
        'unit_price': '14.90',
        'stock': 30,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'nori', 'trucha', 'palta'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/3z7g7E5Njy8kqJDA3-300-x.webp',
    },
    {
        'name': 'Nigiri de Langostino',
        'description': 'Bolita de arroz de sushi y corte fino de langostino cocido, ideal con nuestra salsa de soya.',
        'sku': 'ENTR-NIL-31',
        'unit_price': '7.90',
        'stock': 50,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'langostino cocido', 'salsa de soya'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/wyhsyphRGJWBB6qfR-300-x.webp',
    },
    {
        'name': 'Nigiri de Salmón',
        'description': 'Bolita de arroz de sushi y corte fino de salmón, ideal con nuestra salsa de soya.',
        'sku': 'ENTR-NIS-32',
        'unit_price': '9.90',
        'stock': 50,
        'is_featured': True,
        'ingredients': ['arroz sushi', 'salmón', 'salsa de soya'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/Pjxm6JmLnar5Mambk-300-x.webp',
    },
    {
        'name': 'Nigiri de Trucha',
        'description': 'Bolita de arroz de sushi y corte fino de trucha asalmonada, ideal con nuestra salsa de soya.',
        'sku': 'ENTR-NIT-33',
        'unit_price': '7.90',
        'stock': 50,
        'is_featured': False,
        'ingredients': ['arroz sushi', 'trucha asalmonada', 'salsa de soya'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/hC2FF253RSqhqagXf-300-x.webp',
    },
    {
        'name': 'Sashimi de Langostino',
        'description': '04 cortes de langostino fresco servidos con salsa shoyu, gari y wasabi.',
        'sku': 'ENTR-SHL-34',
        'unit_price': '16.90',
        'stock': 25,
        'is_featured': False,
        'ingredients': ['langostino fresco', 'salsa shoyu', 'gari', 'wasabi'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/3t3PBvAArhzDpXSbm-300-x.webp',
    },
    {
        'name': 'Sashimi de Salmón',
        'description': '04 cortes de langostinos blanqueados servidos con salsa shoyu, gari y wasabi.',
        'sku': 'ENTR-SHS-35',
        'unit_price': '20.90',
        'stock': 25,
        'is_featured': True,
        'ingredients': ['salmón', 'salsa shoyu', 'gari', 'wasabi'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/zQCdD5uucfSJqA9LJ-300-x.webp',
    },
    {
        'name': 'Sashimi de Trucha',
        'description': '04 cortes de trucha asalmonada servidos con salsa shoyu, gari y wasabi.',
        'sku': 'ENTR-SHT-36',
        'unit_price': '15.90',
        'stock': 25,
        'is_featured': False,
        'ingredients': ['trucha asalmonada', 'salsa shoyu', 'gari', 'wasabi'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/xwLmy5avoNrdCndrN-300-x.webp',
    },
    # ── FUSIONADOS ────────────────────────────────────────────────────────────
    {
        'name': 'Combinado Tipakay',
        'description': 'Arroz chaufa de pollo con pollo tipakay y tiras de wantán frito.',
        'sku': 'FUSI-TIP-37',
        'unit_price': '18.90',
        'stock': 50,
        'is_featured': False,
        'ingredients': ['arroz chaufa', 'pollo tipakay', 'wantán frito'],
        'image_url': 'https://tofuu.getjusto.com/orioneat-local/resized2/dfAYnj5S8LX7cxsfk-300-x.webp',
    },
]


class Command(BaseCommand):
    help = 'Carga productos del menú de Mr. Sushi en la base de datos'

    def add_arguments(self, parser):
        parser.add_argument('--clear', action='store_true', help='Elimina todos los productos antes de sembrar')

    def handle(self, *args, **kwargs):
        if kwargs['clear']:
            count, _ = Product.objects.all().delete()
            self.stdout.write(self.style.WARNING(f'{count} productos eliminados.'))

        created = 0
        updated = 0
        for data in PRODUCTS:
            sku = data.pop('sku')
            _, is_new = Product.objects.update_or_create(sku=sku, defaults=data)
            data['sku'] = sku
            if is_new:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(f'{created} productos creados, {updated} actualizados.'))
