# Generated by Django 6.0.6 on 2026-06-22 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Reservada'), ('occupied', 'Ocupada')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='warehouses.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'number')},
            },
        ),
    ]
