# Generated by Django 6.0.6 on 2026-06-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='floors',
            field=models.IntegerField(default=1),
        ),
    ]
